### ISSUE TITLE
Требования к четвёртому релизу

### ISSUE THREAD

**Issue by nvamelichev** [kaledinandrew/TicTacToeOnline#13]
**Долги с третьего релиза:**
- [x] Клиентскую часть проекта **тоже нужно упаковать в исполняемый артефакт**. Она у вас довольно простая, поэтому можно заюзать GraalVM native-image - получится очень быстро стартующий бинарник под целевую платформу (Mac OS, Linux или Windows).

**Багфиксы и улучшения функциональности**
- [x] Предлагать сыграть ещё раз после окончания игры
- [x] Сообщать человеческим языком (а не именем константы из enum'ки), кто победил
- [x] Сделать более дружественные сообщения об ошибках сервера
- [x] Добавить ретраи ввода параметров, если это устранимая ошибка, например, пользователь ввёл что-то неверное
- [ ] [опционально] Список лучших/список рекордов

**Замечания по коду:**
- [x] Переименовать класс: `Variables` - это на самом деле `Constants` :-D
- [x] Загружать базовый URL сервера из конфига. А в `Constants` будут шаблоны типа `{base_url}/my_resource/xxxx` куда вместо `{base_url}` будет подставляться URL сервера, загруженный из конфига. Кстати, если у вас в Constants только шаблоны URL'ов сервисов, его имеет смысл переименовать в `ServiceUrls` или что-то вроде того. А если шаблоны URL'ов юзаются только в коде клиента, можно вообще переместить их в класс клиента и сделать private, чтобы никто на них больше нигде не завязывался :-)
- [x] Конструкция `try-with-resources` очень помогает при работе с вводом-выводом. Пожалуйста, используйте её, чтобы у вас все файлы и потоки закрывались надёжно!

**Требования к четвёртому релизу:**
- [x] В Github Actions успешно настроена **компиляция проекта и запуск тестов** на каждый коммит в ветке `main` и в пул-реквестах.

[опционально] **Бонусы к четвёртому релизу:**
- [ ] `+0.05`: Настроена сборка проекта из ветки `main` в исполняемый артефакт (докер-образ, native-image, jlink/jpackage).
  - В случае Docker-образа собранный образ должен загружаться в репозиторий контейнеров, например, в DockerHub.
  - В случае native-image и jlink/jpackage собранный бинарник или инсталляционный пакет должны попадать в раздел "Releases" вашего проекта на гитхабе.

**Comment by necroshine0** [comment]
Собрал клиент через Graaal VM, но под Windows
В ближайшее время накидаю процесс сборки в README
Сборка под UNIX, увы, не ко мне (
