### ISSUE TITLE
Замечания по CRC-карточкам

### ISSUE THREAD

**Issue by nvamelichev** [kaledinandrew/TicTacToeOnline#8]
Пока карточки "сыроваты": в частности, совсем нет описания классов, описание атрибутов класса смешано с ответственностью (методами) и т.д.

После исправления этих замечаний посмотрю CRC-карточки повторно и напишу, нужно ли ещё что-то уточнять/править или можно уже приступать к уточнённому проектированию, используя UML-диаграммы

- [x] Предлагаю выделить карточки в отдельный документ или страничку на вики, читать в README очень неудобно :-(
- [x] В карточках нужно **прежде всего** описать классы ("что это за штука и для чего"), ответственность и взаимодействия. А уже ПОТОМ можно атрибуты классов, и то это в целом опционально. Описывайте атрибут класса только если он важен - лишняя детализация на этапе высокоуровневого проектирования скорее вредна.
- [x] GameField: смысл атрибута "Shape" надо раскрыть. По сути имелся в виду размер поля - самый просто способ это либо Size (размер стороны поля), либо Width+Height (высота+ширина), если вы разрешаете НЕквадратное поле. Хотя крестики-нолики на НЕ**прямоугольном** поле были бы интересным нововведением, можно об этом подумать на будущее :-D
- [x] В GameSession рекомендую применить паттерн "наблюдатель", чтобы клиент не опрашивал сессию о состоянии поля, а сессия ему присылала информацию "поле изменилось, вот в таких-то клеточках надо нарисовать X и O". 
При этом внутри GameSession можно (и даже пока рекомендуется!) оставить поллинг, просто рассылать слушателям оповещения о диффах, если поле в GameSession не совпало с полем сервера. Сложные схемы с пушами можно будет пробовать, когда уже будет простое решение с поллингом И будет свободное время для экспериментов :-)

**Comment by necroshine0** [comment]
Про прямоугольное поле -- интересно.
Я поэтому и предложил сделать квадратное поле больших размеров с придуманными правилами, и это выглядит как фишка проекта. Подумаем над этим и разберем остальные советы, спасибо!

**Comment by nvamelichev** [comment]
Посмотрел обновлённые CRC-карточки, вижу хороший прогресс :-)

Вот ещё несколько замечаний:
- [x] Console: этот класс явно взаимодействует с сеансом игры (GameSession) чтобы выполнять свои обязанности, но в CRC-карточке это не отражено, отражено только взаимодействие GameSession с Console. Как мне кажется, основное взаимодействие тут всё-таки Console инициирует по требованию от пользователя, а в остальном Console просто реагирует на события, порождаемые GameSession'ом (если вы реализуете в GameSession'е паттерн "наблюдатель")
- [x] Всё ещё многовато деталей. А именно, поля классов прописаны прям очень конкретно, с типами данных и т.п., хотя типы и состав полей могут ещё сто раз поменяться. Рекомендую их описать в более общем виде. Например, вместо GameField.Size: tuple(int,int) написать что-то вроде "Размер игрового поля (ширина x высота)". Такое описание допускает массу различных реализаций, т.к. в высокоуровневой модели почти не важно, как у вас данные полей хранятся - массивом, кортежем, двумя полями-чиселками, классом с двумя чиселками...

**Comment by nvamelichev** [comment]
Осталась пара мелочей:
- [x] Rules -> поля можно не перечислять, слишком много подробностей
- [x] Переименовать SessionListener /.-> SessionObserver. + в наблюдателе нужны методы для регистрации гейм-сессии (а в общем случае нужны методы для регистрации слушателей событий)

**Comment by necroshine0** [comment]
Т.е. просто сделать метод, который будет в добавлять в список слушателей и метод, который на событие onClick будет запускать итерацию по объектам этого списка, вызывая у каждого метод onClick()?

**Comment by nvamelichev** [comment]
> Т.е. просто сделать метод, который будет в добавлять в список слушателей и метод, который на событие onClick будет запускать итерацию по объектам этого списка, вызывая у каждого метод onClick()?

Типа того, ага :-). Для списка рекоменду.ю использовать что-нибудь потокобезопасное, например, в этом случае хорош `CopyOnWriteArrayList`: листенеров обычно немного, а `CopyOnWriteArrayList` при итерации всегда использует консистентный стейт. Всё потому, что при любом изменении списка массив с элементами создаётся новый, а созданные до изменения итераторы просто используют старый массив, который может, разве что, не содержать нескольких последних изменений списка :-)

**Comment by nvamelichev** [comment]
Заметил ещё интересную мелочь в ваших CRC-карточках: у вас пользователь выбирает, крестиками он играет или ноликами (User -> Fields ->Symbol (X or O)). Этот выбор его оппоненту виден, или это просто настройка, каким символом (X или O или каким-нибудь ещё) отображать занятые пользователем клетки поля?

**Comment by necroshine0** [comment]
Смотрите, у меня пока такой подход
Вы же знаете игру WoT (танчики)? Там всегда есть две команды -- союзная зеленая, вражеская красная. Так вот игрок всегда играет за союзную команду. При этом есть режим цветовой слепоты, когда красный цвет меняется на фиолетовый, и это видит только тот игрок, который включил этот режим у себя на клиенте.
Вот на первоначальном этапе мы планируем сделать именно так. Игрок выбирает себе символ, а у противника какой-то другой (вероятно, из какой-то конфигурации). И это отображается только у него, т.е. у противника может быть другая визуализация. Такой подход поможет избежать проблем, когда, например, оба игрока хотят ставить крестики.

Отвечая на вопрос -- нет, оппонент не видит выбор игрока, его видит сам игрок. В перспективе можно сделать так, чтобы каждый видел символ каждого, но в таком случае придется выдумывать, как решать конфликт интересов. На данный момент это не первостепенная задача.

**Comment by nvamelichev** [comment]
CRC-карточки приняты :+1:
